### PR TITLE
Merge our contributions?

### PR DESCRIPTION
**Pull request by Shadowtail117**
(@EpicSupermind) Turns out I'm working on the same thing as you. You were here first, so I'll just open a pull request and let you decide what to add in (if anything).
Basic rundown of what I've done:

- Taken all of the pictures from the old page and put them into /Game_Modifiers/pictures/. 

- Replaced (most, some were removed) the  tags with inline tags so the pictures show, and

- Made some grammar fixes. 

Unfortunately, some of the images are probably too big, plus they all break the text. Not sure how to fix it in markdown, but if you know go ahead. 

(Also, looks like this pull request is also taking in some older commits from April 4th onward. Sorry about that.)

### CODE REVIEW

**Comment by EpicSupermind** [comment]
Sure, can you rename the image folder to img? because that's where all my images link to.

**Comment by EpicSupermind** [comment]
ok nevermind, i'm mostly just gonna use the grammar fixes and that's it. Most of this is stuff i've already done, like change the images to gfm, and yeah, for future reference, images like that are supposed to be relative-relative, `/pictures/Easy.png` or `/wiki/Game_Modifiers/pictures/Easy.png`. I'll try to add all your grammar changes tommorow, and thanks!

**Comment by EpicSupermind** [comment]
Also, it's okay that the images aren't fitting. The wiki uses a very high resolution image and resizing them makes them drop in quality. There's also no good GFM way to resize it. The struggles of not haveing HTML.

**Comment by Shadowtail117** [comment]
There you go, renamed the folder to img.

**Comment by EpicSupermind** [comment]
ok, rather than merging your file into mine, i'll just type in the grammar fixes and push it to ppy:osu-wiki

**Pull request closed without merging**
